# Generated by Django 6.0 on 2025-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='foto_principal',
            field=models.ImageField(upload_to='imobiliaria/media/'),
        ),
    ]
